### PR TITLE
houdhakker's backend documentation update

### PR DESCRIPTION
**Pull request by Arne-van-der-Lei**

### CODE REVIEW

**Comment by igorantun** [comment]
Merge conflicts much

**Comment by Arne-van-der-Lei** [comment]
wat files cant be merged

**Comment by samhmills** [comment]
Alright, I'll see if I can handle this without changing too much, in future, maybe we should use a staging branch so that changes merged don't go straight to the master, and thus, shown on the site

**Comment by samhmills** [comment]
This has been successfully merged manually, I will therefore close this pull request, thanks!

**Comment by samhmills** [comment]
As a side note, please make sure your fork matches the master branch of this project 100%! There's a lot of conflicts here that could have been fixed/avoided :smile:

**Pull request closed without merging**
