### PR TITLE
Missing nameChangedRoom

### PR DESCRIPTION
**Pull request by Burkes**
today we learn about a new undocumented event

### CODE REVIEW

**Comment by samhmills** [comment]
I would make the suggestion for a more SFW example to be used...

**Comment by Burkes** [comment]
Should I remove the screenshot as well? lol

**Comment by igorantun** [comment]
If possible, yes, I would at least change the screenshot as well.. lol

**Review by xBytez — APPROVED** [review]
This looks  perfect.

**Comment by xBytez** [comment]
I did a squash merge so the screenshot would not be included.

**Comment by samhmills** [comment]
Thanks, 

Trying to let you guys take over this as I'm not in a delegated position of authority with this anymore :)

**Comment by xBytez** [comment]
@Hunchmun However I consider this community driven and I still consider you part of that, even more considering you started this. I also value your opinion :)

**Pull request merged**
