### PR TITLE
[WIP] general socket documentation

### PR DESCRIPTION
**Pull request by goto-bus-stop**
TODO:
- [x] Connecting
- [x] Sending messages

### CODE REVIEW

**Comment by igorantun** [comment]
Let me know when this is ready to be merged.

**Comment by goto-bus-stop** [comment]
Just some links to finish up.

**Comment by goto-bus-stop** [comment]
Guess this should go to `staging` as well.

**Comment by goto-bus-stop** [comment]
Moved to #15

**Pull request closed without merging**
